import type { GetStaticPropsContext, NextPage } from 'next';
import { useTranslations } from 'next-intl';
import Head from 'next/head';
import Generate from '../components/generate/Generate';

const Home: NextPage = () => {
    const t = useTranslations('Generate');
    return (
        <>
            <Head>
                <title>{t('title')}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Generate />
        </>
    );
};

export async function getStaticProps({ locale }: GetStaticPropsContext) {
    return {
        props: {
            messages: (await import(`@/messages/${locale}.json`)).default,
        },
    };
}

export default Home;
