import type { NextPage } from "next";
import Head from "next/head";
import Generate from "../components/generate/Generate";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Generate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Generate />
    </>
  );
};

export default Home;
